[build]
  command = "npm run build && cp -r public .next/"
  publish = ".next"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["next"]

[[redirects]]
  from = "/api/*"
  to = "https://api.dev.debita.io/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
